### ISSUE TITLE
New Issue with get_var_flanks.py

### ISSUE THREAD

**Issue by DM2016** [NCBI-Hackathons/PSST#4]
This is the latest error that I get trying to use get_var_flanks.py.  This time the mTOR_snp_accessions.txt file does not have 'rs' in the entries.

**below command:**
python get_var_flanks.py -i mTOR_snp_accessions.txt -e diego.morales@nih.gov -o mTOR_snp_flanks.txt

**Results:**

Traceback (most recent call last):
  File "get_var_flanks.py", line 86, in <module>
    main(sys.argv)
  File "get_var_flanks.py", line 82, in main
    flanking_sequences = get_var_flanking_sequences(accessions,email)
  File "get_var_flanks.py", line 12, in get_var_flanking_sequences
    for record in records:
  File "/home/moralesdia/.local/lib/python2.7/site-packages/Bio/Entrez/Parser.py", line 286, in parse
    self.parser.Parse(text, False)
  File "/home/moralesdia/.local/lib/python2.7/site-packages/Bio/Entrez/Parser.py", line 390, in endElementHandler
    raise RuntimeError(value)
RuntimeError: Empty id list - nothing todo

**Comment by sean-la** [comment]
Please email me the file `mTOR_snp_accessions.txt`!

**Comment by DM2016** [comment]
Hi Sean,

Here is the file.

Diego


________________________________

**Comment by sean-la** [comment]
It seems to be working on my local machine. What version of biopython are you using? Which branch are you on? If it's master, is it the latest commit?

**Comment by DM2016** [comment]
Thank you for the file Sean.

I didn't use biopython for this.  Until recently, I didn't know that I had to use it for this or how to connect biopython to this program.

All I did was use the get_var_flanks.py program.

-Diego


________________________________

**Comment by DM2016** [comment]
May I ask how you connected your program to biopython when you ran it?

-Diego


________________________________

**Comment by sean-la** [comment]
Biopython is listed as a dependency in the PSST repository, so these dependencies apply for all programs used by PSST. Run `pip install biopython`, though if you're using NCBI's servers, this command might fail so you're going to need to find a way to install Biopython in a custom folder. If you need help, message the NCBI help desk for linux.

**Comment by DM2016** [comment]
Hi Sean
I think I've found out what was wrong with the file when I tried running it on PSST
There was an empty space at the bottom of my input file that was screwing everything up.
Anyways, I've run it again and it's working perfectly now.
I think a potential issue that we may want to address in future versions of this code is how to deal with blank spaces?
I have set up an account and discussion on gitter/github.
Best,
Diego



________________________________

**Comment by sean-la** [comment]
Oh, that's great to hear that you found the issue! I'll add a bug fix to that file. 

Thanks for your help!
